export const ADMIN_PASSWORD_MODAL_OPEN = "ADMIN_PASSWORD_MODAL_OPEN";
export const ADMIN_PASSWORD_MODAL_CLOSE = "ADMIN_PASSWORD_MODAL_CLOSE";

export const ADMIN_PROFILE_INFO_MODAL_OPEN = "ADMIN_PROFILE_INFO_MODAL_OPEN";
export const ADMIN_PROFILE_INFO_MODAL_CLOSE = "ADMIN_PROFILE_INFO_MODAL_CLOSE";


export const DIRECTOR_PASSWORD_MODAL_OPEN = "DIRECTOR_PASSWORD_MODAL_OPEN";
export const DIRECTOR_PASSWORD_MODAL_CLOSE = "DIRECTOR_PASSWORD_MODAL_CLOSE";

export const DIRECTOR_PROFILE_INFO_MODAL_OPEN = "DIRECTOR_PROFILE_INFO_MODAL_OPEN";
export const DIRECTOR_PROFILE_INFO_MODAL_CLOSE = "DIRECTOR_PROFILE_INFO_MODAL_CLOSE";


export const CLINICIAN_PASSWORD_MODAL_OPEN = "CLINICIAN_PASSWORD_MODAL_OPEN";
export const CLINICIAN_PASSWORD_MODAL_CLOSE = "CLINICIAN_PASSWORD_MODAL_CLOSE";

export const CLINICIAN_PROFILE_INFO_MODAL_OPEN = "CLINICIAN_PROFILE_INFO_MODAL_OPEN";
export const CLINICIAN_PROFILE_INFO_MODAL_CLOSE = "CLINICIAN_PROFILE_INFO_MODAL_CLOSE";