
export const USER_ACCOUNT_TYPE = "USER_ACCOUNT_TYPE";
// const ACCOUNT_USERNAME = "ACCOUNT_USERNAME";
// const ACCOUNT_TYPE = "ACCOUNT_TYPE";
export const ACCOUNT_PROFILE_URL = "ACCOUNT_PROFILE_URL";
